const heroesActionTypes = {
  FETCH_HEROES_START: 'FETCH_HEROES_START',
  FETCH_HEROES_SUCCESS: 'FETCH_HEROES_SUCCESS',
  FETCH_HEROES_FAIL: 'FETCH_HEROES_FAIL',
};

export default heroesActionTypes;
